model: 'lstm'
train_samples: 50000
valid_samples: 10000
test_samples: 10000
epochs: 100
embedding_dim: 128
hidden_dim: 256
num_layers: 1
batch_size: 32
learning_rate: 0.001
patience: 10
dropout: 0.2
teacher_forcing_prob: 1.0
docstring_vocab_size: 16000
docstring_vocab_min_frequency: 2
seed: 42
checkpoint_dir: './checkpoints/models/lstm'
raw_dataset_path: "./data/raw/dataset/python/"
processed_dataset_path: "./data/processed/models/"