model: 'transformer'
train_samples: 50000
valid_samples: 5000
test_samples: 5000
epochs: 100
patience: 10
n_heads: 4
d_model: 256
ff_units: 512
dropout: 0.1
num_layers: 4
learning_rate: 0.0001
batch_size: 4
docstring_vocab_size: 16000
docstring_vocab_min_frequency: 2
seed: 42
checkpoint_dir: './checkpoints/models/transformer/'
raw_dataset_path: "./data/raw/dataset/python/"
processed_dataset_path: "./data/processed/models/"