model: 'transformer'
train_samples: 100
valid_samples: 20
test_samples: 20
epochs: 100
patience: 5
n_heads: 4
d_model: 128
ff_units: 512
dropout: 0.1
num_layers: 2
learning_rate: 0.0001
batch_size: 8
docstring_vocab_size: 10000
docstring_vocab_min_frequency: 2
seed: 42
checkpoint_dir: './checkpoints/models/lstm/'
raw_dataset_path: "./data/raw/dataset/python/"
processed_dataset_path: "./data/processed/models/"