train_data_length: 5000
valid_data_length: 1000
embedding_dim: 128
hidden_dim: 256
batch_size: 8
num_epochs: 100
learning_rate: 0.001
patience: 5
teacher_forcing_prob: 0.5
checkpoint_dir: './../../checkpoints/model01/ast/'