train_data_length: 5000
valid_data_length: 1000
test_data_length: 1000
num_epochs: 100
patience: 5
checkpoint_dir: './../../checkpoints/notebooks/model05/'
n_heads: 4
d_model: 128
ff_units: 768
dropout: 0.1
n_layers: 2
learning_rate: 0.0001
batch_size: 16